user.access.token=${USER_ACCESS_TOKEN}

##############################
####  AUTH CONFIGURATION  ####
##############################
jwt.secret=${JWT_SECRET}
#Access token expiry 15 minutes
jwt.accessTokenValidity=900000
#Refresh token expiry = 7 days
jwt.refreshTokenValidity=604800000

encryption.password=${ENCRYPTION_PASSWORD}
encryption.salt=${ENCRYPTION_SALT}

# Hibernate (JPA) Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Database configuration
###############################
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver