user.access.token=my-secure-gateway-token

##############################
####  AUTH CONFIGURATION  ####
##############################
jwt.secret=oirbkrier0ubhjnfooerrb,eroi;erheroherrb eroh;erjrpijreerbmeruer;verjl erou;er ererlg eriverlh
#Access token expiry 2 hours
jwt.accessTokenValidity=7200000

#Refresh token expiry = 7 days
jwt.refreshTokenValidity=604800000

encryption.password=myVerySecretKey123oirbkrier0ubhjnfooerrb
encryption.salt=1234567890abcdef

# Hibernate (JPA) Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Database configuration
###############################
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver