spring.application.name=USER-SERVICE
server.port=8022

spring.profiles.active=dev

# LDAP configuration
ldap.server.host=${LDAP_SERVER_HOST}
ldap.server.port=${LDAP_SERVER_PORT}
ldap.domain=${LDAP_DOMAIN}
